# Generated by Django 3.1.7 on 2021-03-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('accounts', '0003_auto_20210314_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='major_subjects',
            field=models.ManyToManyField(blank=True, to='courses.Subject'),
        ),
    ]
