# Generated by Django 3.2.4 on 2021-06-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210613_0505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='instructorprofile',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='profile_images/default.png', upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='facebook_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='github_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='instagram_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='twitter_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
