# Generated by Django 3.2.4 on 2021-06-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210613_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='achievements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='objectives',
            field=models.TextField(blank=True, null=True),
        ),
    ]
