# Generated by Django 3.2.4 on 2021-08-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210627_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='trashed',
            field=models.BooleanField(default=False),
        ),
    ]
