# Generated by Django 3.2.4 on 2021-07-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20210727_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('review', 'a review'), ('comment', 'a comment'), ('reply', 'a reply'), ('enrolling', 'an enrolling')], default='review', max_length=60),
        ),
    ]
