# Generated by Django 3.2.4 on 2021-08-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_profile_image'),
        ('courses', '0018_auto_20210801_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='students_viewed',
            field=models.ManyToManyField(blank=True, to='accounts.StudentProfile'),
        ),
    ]
