# Generated by Django 3.2.4 on 2021-08-03 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_profile_image'),
        ('courses', '0020_acheivements'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Acheivements',
            new_name='Acheivement',
        ),
    ]
