# Generated by Django 3.2.4 on 2021-08-03 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_profile_image'),
        ('courses', '0021_rename_acheivements_acheivement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acheivement',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='acheivement',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='accounts.studentprofile'),
        ),
    ]
