# Generated by Django 3.2.4 on 2021-08-03 07:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_auto_20210803_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='acheivement',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 8, 3, 7, 6, 46, 159804, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
