# Generated by Django 3.2.4 on 2021-08-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_profile_image'),
        ('courses', '0023_acheivement_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='students_viewed',
            field=models.ManyToManyField(blank=True, to='accounts.StudentProfile'),
        ),
    ]
