# Generated by Django 3.2.4 on 2021-08-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_content_students_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='trashed',
            field=models.BooleanField(default=False),
        ),
    ]
